{
	"version": 1772119386,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/playeranimations-sheet0.png",
		"images/playeranimation-sheet0.png",
		"images/player-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tilemap5.png",
		"images/tilemap4.png",
		"images/tiledbackground.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/bg-sheet0.png",
		"media/caught a pokemon! sound effect - mrssoundfx (128k).ogg",
		"media/pokemon music for relaxingstudying (gen 45) - sleepy snorlax (128k).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}